#!/bin/sh
#
#  test-relabel-newick - test script for relabel-newick
#  Copyright (C) 2017  Marco van Zwetselaar <io@zwets.it>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Home: https://github.com/zwets/phylo-utils

TMP_FILE="$(mktemp)"

# Function to exit this script with an error message on stderr
err_exit() {
    echo "$(basename "$0"): $*" >&2
    [ ! -f "$TMP_FILE" ] || rm -f "$TMP_FILE"
    exit 1
}

SCRIPT="../relabel-newick"
[ -x "$SCRIPT" ] || err_exit "no such executable script: ../relabel-newick"

TREE_FILE="tree.newick"
[ -f "$TREE_FILE" ] || err_exit "no such file: $TREE_FILE"

RULES_FILE="rules.sample"
[ -f "$RULES_FILE" ] || err_exit "no such file: $RULES_FILE"

# Simplest possible test: do not rewrite at all
echo -n "Test: simplest ... "
echo "" | "$SCRIPT" "$TREE_FILE" > "$TMP_FILE"
diff "$TREE_FILE" "$TMP_FILE" || err_exit "simplest test: file not identical to $TREE_FILE: $TMP_FILE"
echo "OK"

# Testing --extract, should by default give identity mapping
echo -n "Test: extract ... "
"$SCRIPT" --extract "$TREE_FILE" | sort -u | "$SCRIPT" "$TREE_FILE" > "$TMP_FILE"
diff "$TREE_FILE" "$TMP_FILE" || err_exit "extract test: file not identical to $TREE_FILE: $TMP_FILE"
echo "OK"

# Test on the tree and rules files
echo -n "Test: rewrite ... "
"$SCRIPT" "$TREE_FILE" "$RULES_FILE" | fgrep -vq '/' || err_exit "rewrite test: output should not contain '/'"
echo "OK"

rm -f "$TMP_FILE"
exit 0

# vim: sts=4:sw=4:et:ai:si
