#!/bin/bash
#
#  test-relabel-newick - test script for relabel-newick
#  Copyright (C) 2017  Marco van Zwetselaar <io@zwets.it>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Home: https://github.com/zwets/phylo-utils

TMP_FILE="$(mktemp "$(basename "$0").XXXXXX")"

# Function to exit this script with an error message on stderr
err_exit() {
    echo "$(basename "$0"): $*" >&2
    [ ! -f "$TMP_FILE" ] || rm -f "$TMP_FILE"
    exit 1
}

SCRIPT="../relabel-newick"
[ -x "$SCRIPT" ] || err_exit "no such executable script: ../relabel-newick"

TREE_FILE="tree.newick"
[ -f "$TREE_FILE" ] || err_exit "no such file: $TREE_FILE"

RULES_FILE="rules.sample"
[ -f "$RULES_FILE" ] || err_exit "no such file: $RULES_FILE"

# Function to exit on failed test
fail() {
    echo "FAIL${1:+: $1}" >&2
    rm -f "$TMP_FILE"
    exit 1
}

# Simplest possible test: do not rewrite at all
echo -n "Test: simplest ... "
echo "" | "$SCRIPT" "$TREE_FILE" > "$TMP_FILE" && cmp -s "$TREE_FILE" "$TMP_FILE" || fail
echo "OK"

# Testing --extract, should by default give identity mapping
echo -n "Test: extract ... "
"$SCRIPT" --extract "$TREE_FILE" | sort -u | "$SCRIPT" "$TREE_FILE" > "$TMP_FILE" && cmp -s "$TREE_FILE" "$TMP_FILE" || fail
echo "OK"

# Test on the tree and rules files
echo -n "Test: rewrite ... "
"$SCRIPT" "$TREE_FILE" "$RULES_FILE" > "$TMP_FILE" && cmp -s "$TMP_FILE" "test.output" || fail "test output does not match test.output"
echo "OK"

rm -f "$TMP_FILE"
exit 0

# vim: sts=4:sw=4:et:ai:si
